### ISSUE TITLE
Question: Include Tags in Post Description

### ISSUE THREAD

**Issue by oliverlabs** [mischavandenburg/blog#1]
Hi Mischa, 

Could you please explain how you modified the PaperMod theme to include post tags under post previews? Is that done via custom css?

Here's what I mean:

<img width="511" alt="image" src="https://github.com/mischavandenburg/blog/assets/70239916/4c30aba7-08c4-4035-ab3e-40b6bc53d08b">

Cheers!

**Comment by mischavandenburg** [comment]
Hi @oliverlabs, sorry for the late response! I realize I need to keep an eye on notifications on GitHub these days :) I did not do any customization to enable these tags. I'm using the PapermodX theme though, which is a fork of Papermod, so perhaps it is a default feature in that theme? 

You can check out the config.yaml in this repo to see my configuration for the theme.
